version: '3.4'

services:
  someting:
    image: ${DOCKER_REGISTRY-}someting
    build:
      context: .
      dockerfile: someting/Dockerfile
    depends_on:
        -  db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: db
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD='Portfolio1@3
        - MSSQL_PID=Express
    ports:
     - "1433:1433"
