[project]
name = "cito1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "cryoelite", email = "itscryonim@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
cito1 = "cito1:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
