name: test_dart
description: Testing various dart utilities.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  xml: ^5.1.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
