#based on https://stackoverflow.com/a/47600762/13036358
- name: Test Configuration Playbook
  hosts: containers
  become: true
  vars_files:
      - /root/development/group_vars/vars.yml
  
  tasks:
    - name: Update and Upgrade
      become: true
      apt:
        update_cache: yes
        upgrade: yes
    
    - command: "echo 'Debug Yo!'"
      


