name: citoflutter
description: CITO (Code I Test On). General Testing flutter app.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  adobe_xd: ^1.0.0+1
  google_fonts: ^1.1.1
  flutter_local_notifications: ^4.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/bhavupdate.mp3
