version: "3.9"

services:
  test-image:
    image: ansible-test
    build:
      context: ..
      dockerfile: "docker/Dockerfile"
    ports:
      - "8007:80"
      - "8008:443"
    env_file:
      - .env

